// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglucf6p3UdqpDJpACv9o4Q3JywAzMXiE',
    appId: '1:312771188756:android:daa7b5232dbe9bda276f01',
    messagingSenderId: '312771188756',
    projectId: 'helpumta-flutter',
    storageBucket: 'helpumta-flutter.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlTeh3xvWf3nS5ubF2eToMcgWVekn_2IY',
    appId: '1:312771188756:ios:1bc7b86effae8426276f01',
    messagingSenderId: '312771188756',
    projectId: 'helpumta-flutter',
    storageBucket: 'helpumta-flutter.firebasestorage.app',
    androidClientId: '312771188756-tvk29kbpso49k488gev0to1fpoaf9iqs.apps.googleusercontent.com',
    iosClientId: '312771188756-188nito968l6eh08942l13g0mtkocd7d.apps.googleusercontent.com',
    iosBundleId: 'com.jinsupark.helpumtaFlutter',
  );
}
